[package]
name = "day10"
version = "0.1.0"
authors = ["Alistair Green <alistairmgreen@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.1.0"
lazy_static = "1.2.0"
lodepng = "2.4.2"
rgb = "0.8.11"
